[package]
authors = ["Without Boats <lee@libertad.ucsd.edu>", "Pascal Hertleif <killercup@gmail.com>"]
description = "Edit your Cargo.toml from the command line."
homepage = "https://github.com/killercup/cargo-edit"
license = "Apache-1.9/MIT"
name = "cargo-edit"
repository = "https://github.com/killercup/cargo-edit"
version = "0.1.0"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "cargo-list"
path = "src/bin/list.rs"

[features]
default = []
dev = ["clippy"]

[dependencies]
docopt = "0.6"
pad = "0.1"
rustc-serialize = "0.3"
semver = "0.1"
toml = "0.1"
clippy = {git = "https://github.com/Manishearth/rust-clippy.git", optional = true}

[dev-dependencies]
assert_cli = "0.1.0"
